sudo: false
language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.0"
  - "4.1"
  - "4.2"
services:
    - mongodb
    - redis-server
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - python2.7
    - python2.7-dev
after_success:
    - npm run coveralls
